### ISSUE TITLE
Can log in as existing CJ user with wrong CJ password

### ISSUE THREAD

**Issue by raddick** [sciserver/sciserver-sso-portal#20]
I registered a portal account for user legacy_091 deliberately using a password different from the one Mitya created for the legacy users. I was able to register despite the wrong password. Now when I log in as legacy_091, I can only log in using the new password I created.

Somehow the portal is not checking old CasJobs passwords when linking accounts.

**Comment by dmedv** [comment]
Wrong user names... Should be "legacy_user_XXX", not "user_XXX".
